# Site specific settings
title: "WaffleSec"
name: "WaffleSec"
keywords: "WaffleSec, Cyber Security, Programming, Computer"
baseurl: "/wafflesec"
url: "https://maria-waffle.github.io"
description: "WaffleSec Blog"
# cover:
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
# disqus:
twitter:
facebook: 
github: maria-waffle
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
